services:
  navidrome:
    image: deluan/navidrome:latest
    user: "{{ navidrome_user }}:{{ navidrome_user }}" # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "{{ navidrome_dir }}:/data"
      - "{{ music_dir }}:/music:ro"

  slskd:
    image: slskd/slskd
    container_name: slskd
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - "{{ soulseek_dir }}:/app"
      - "{{ music_dir }}:/music:ro"
      - "{{ ebook_dir }}:/ebooks:ro"
    restart: unless-stopped

  lms:
    container_name: lms
    image: lmscommunity/logitechmediaserver
    volumes:
      - "{{ lms_dir }}/config:/config:rw"
      - "{{ music_dir }}:/music:ro"
      - "{{ lms_dir }}/playlist:/playlist:rw"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 9000:9000/tcp
      - 9090:9090/tcp
      - 3483:3483/tcp
      - 3483:3483/udp
    restart: always
    environment:
      - PUID=1000
      - PGID=1000

  mediamtx:
    container_name: mediamtx
    image: bluenviron/mediamtx:latest-ffmpeg
    volumes:
      - "{{ mediamtx_dir }}/mediamtx.yml:/mediamtx.yml:ro"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    network_mode: host
    restart: always
