- import_playbook: include_vault.yml
- import_playbook: docker-server.yml
- import_playbook: cameras-server.yml
# - import_playbook: analytics-server.yml

- hosts: home_assistant
  pre_tasks:
    - name: Setup dirs, users etc
      become: yes
      import_tasks: roles/home-assistant/tasks/pre-deploy.yml
    - name: Setup dirs, users etc
      become: yes
      import_tasks: roles/streaming/tasks/pre-deploy.yml

  roles:
    - home-assistant
    - unifi-controller
    - reverse-proxy
    - streaming
    - storage
    - analytics

  post_tasks:
    - name: Setup mqtt password
      become: yes
      import_tasks: roles/home-assistant/tasks/post-deploy.yml
    - name: Setup Influx users
      # become: yes
      import_tasks: roles/analytics/tasks/post-deploy.yml
