services:
  swag:
    image: linuxserver/swag
    container_name: swag-proxy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/.swag-proxy/:/config
    environment:
      - PGID=1004
      - PUID=1000
      - URL={{ external_proxy_url }}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - TZ=Pacific/Auckland
    ports:
      - "80:80"
      - "443:443"
    networks:
      swag_proxy_net:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10

networks:
  swag_proxy_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"
