---
services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_PASS={{ unifi_mongo_password }}
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      # - MONGO_TLS= #optional
    volumes:
      - "{{ unifi_dir }}/:/config"
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      # - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
    depends_on:
      - unifi-db

  unifi-db:
    image: docker.io/mongo:7.0.0
    container_name: unifi-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD={{ unifi_root_mongo_password }}
      - MONGO_USER=unifi
      - MONGO_PASS={{ unifi_mongo_password }}
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    volumes:
      - "{{ unifi_dir }}/mongo/data:/data/db"
      - "{{ unifi_dir }}/mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro"
    restart: unless-stopped