services:
  homeassistant:
    container_name: homeassistant
    image: lscr.io/linuxserver/homeassistant:latest
    volumes:
      - "{{ home_assistant_dir }}:/config"
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - 8123:8123
    environment:
      - PUID=1001
      - PGID=8123
      - TZ=NZ
    depends_on:
      - mosquitto

  node-red:
    container_name: node-red
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - "{{ node_red_dir }}:/data"
    depends_on:
      - mosquitto
    restart: unless-stopped

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - "{{ mosquitto_dir }}/config:/mosquitto/config"
      - "{{ mosquitto_dir }}/data:/mosquitto/data"
      - "{{ mosquitto_dir }}/logs:/mosquitto/log"
    ports:
      - "1883:1883"
    restart: unless-stopped

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - "{{ zigbee2mqtt_dir }}:/app/data"
      - /run/udev:/run/udev:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro      
    ports:
      # Frontend port
      - 8000:8000
    environment:
      - TZ=NZ
    devices:
      # Make sure this matched your adapter location
      - /dev/ttyUSB0:/dev/ttyACM0
    depends_on:
      - mosquitto

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - "{{ esp_home_dir }}/config:/config"
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
    environment:
      - ESPHOME_DASHBOARD_USE_PING=true

  weewx:
    image: custom_image/weewx
    build:
      context: .
      dockerfile: DockerfileWeewx
    init: true
    restart: unless-stopped
    ports:
     - "9052:80"
    volumes:
      - type: bind
        source: "{{ weewx_home_dir }}"
        target: /data
      - type: bind
        source: "{{ ansible_env.HOME }}/.swag-proxy/www/weewx"
        target: /home/weewx/public_html
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TIMEZONE=NZ
      - WEEWX_UID=1000
      - WEEWX_GID=1000

  opensprinkler-weather:
    image: opensprinkler-weather
    restart: unless-stopped
    ports:
     - "3000:3000"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TIMEZONE=NZ
