---
# Docker compose setup steps

- name: Copy compose source templates
  template:
    src: files/docker-compose.yml
    dest: "{{ streaming_docker_compose_dir }}/docker-compose.yml"
    mode: 0600

- name: Tear down existing services
  community.docker.docker_compose_v2:
    project_src: "{{ streaming_docker_compose_dir }}"
    state: absent

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "{{ streaming_docker_compose_dir }}"
  register: output

- ansible.builtin.debug:
    var: output

- name: Run `docker-compose up` again
  community.docker.docker_compose_v2:
    project_src: "{{ streaming_docker_compose_dir }}"
    build: never
  register: output

- ansible.builtin.debug:
    var: output

- ansible.builtin.assert:
    that: "not output.changed "
